name: Relaciones Geográficas
lang: ES
url: https://www.lancaster.ac.uk/digging-ecm/corpus/
genre:
  - historical

dataset_in_dir: original_data
dataset_out_dir: data
output_columns:
  - Token
  - NER
