name: Paramopama
lang: PT
url: https://github.com/davidsbatista/NER-datasets
genre:
  - newswire
  - blog
  - wikipedia

dataset_in_dir: original_data
dataset_out_dir: data
output_columns:
  - Token
  - NER
